In [5]:
from threading import Thread
from time import sleep
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from deep_translator import GoogleTranslator
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [28]:
driver = webdriver.Firefox()

# driver.get("https://www.booking.com/hotel/pt/the-yeatman.en-gb.html#tab-reviews")
driver.get("https://www.booking.com/hotel/pt/domhenrique.en-gb.html#tab-reviews")
title = driver.title
sleep(10)
#driver.implicitly_wait(10)
driver.find_element(by=By.ID,value='onetrust-accept-btn-handler').click()


# Step 1: Create an empty DataFrame with five columns
df = pd.DataFrame(columns=['name', 'country', 'room_type', 'nr_nights', 'date', 'traveler_type', 'title_review', 'pos_review', 'neg_review', 'score'])

def call_func(df):
    try:
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "d799cd346c")))
        mylst = driver.find_elements(By.CLASS_NAME, value="d799cd346c")
        for elem in mylst:
            def get_text(xpath):
                try:
                    return elem.find_element(by=By.XPATH, value=xpath).text
                except Exception:
                    return ''
            x1 = get_text(".//div[@class='a3332d346a e6208ee469']")
            x2 = get_text(".//span[@class='afac1f68d9 a1ad95c055']")
            x3 = get_text(".//span[@data-testid='review-room-name']")
            x4 = get_text(".//span[@data-testid='review-num-nights']")
            x5 = get_text(".//span[@data-testid='review-stay-date']")
            x6 = get_text(".//span[@data-testid='review-traveler-type']")
            x7 = get_text(".//h3[@data-testid='review-title']")
            x8 = get_text(".//div[@data-testid='review-positive-text']")
            x9 = get_text(".//div[@data-testid='review-negative-text']")
            x10 = get_text(".//div[@class='a3b8729ab1 d86cee9b25']").split('\n')[0].replace(',', '.')
            new_row = {'name': x1, 'country': x2, 'room_type': x3, 'nr_nights': x4, 'date': x5, 'traveler_type': x6, 'title_review': x7, 'pos_review': x8, 'neg_review': x9, 'score': x10}
            new_row_df = pd.DataFrame([new_row])
            df = pd.concat([df, new_row_df], ignore_index=True)
        return df
    except Exception as e:
        print(f"Error scraping reviews: {e}")
        return df

number = 0
max = 505

while(number<max):
    df=call_func(df)
    try:
        next_button = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "//button[@aria-label='Next page']")))
        next_button.click()
        number += 1
    except Exception as e:
        print(f"Stopped at page {number}, possibly no more reviews. Error: {e}")
        break

driver.quit()

Stopped at page 503, possibly no more reviews. Error: Message:

In [30]:
number

503

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5037 entries, 0 to 5036
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           5037 non-null   object
 1   country        5037 non-null   object
 2   room_type      5037 non-null   object
 3   nr_nights      5037 non-null   object
 4   date           5037 non-null   object
 5   traveler_type  5037 non-null   object
 6   title_review   5037 non-null   object
 7   pos_review     5037 non-null   object
 8   neg_review     5037 non-null   object
 9   score          5037 non-null   object
dtypes: object(10)
memory usage: 393.6+ KB

In [34]:
df.head(15)

,name,country,room_type,nr_nights,date,traveler_type,title_review,pos_review,neg_review,score
0,Christina,Belgium,Comfort Double Room,3 nights ·,January 2025,Family,Exceptional,"Room was spacious, clean and with good amenities",N/A,Scored 10
1,Helen,United Kingdom,Comfort Single Room,2 nights ·,March 2025,Solo traveller,Well placed hotel with great facilities,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Scored 9.0
2,Irene,United Kingdom,Comfort King Room,2 nights ·,March 2025,Couple,Very clean with professional staff and very go...,Staff is very friendly and extremely professio...,Nothing,Scored 9.0
3,Andrea,Hungary,Plus Comfort Suite,4 nights ·,February 2025,Family,"Elegant, good hotel in the center",We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...",Scored 9.0
4,Anjali,Canada,Comfort Family Room,2 nights ·,February 2025,Family,Good location and nice hotel with spacious units.,Location and size of the unit. Comfortable for...,,Scored 8.0
5,Hannah,United Kingdom,Comfort Suite,3 nights ·,February 2025,Family,Excellent hotel for city break,"Lovely rooftop bar, really nice room, excellen...",Not the nicest looking building from the outsi...,Scored 8.0
6,Halmcc,United States,Comfort Single Room,2 nights ·,February 2025,Solo traveller,Great hotel and stay. I would definitely return.,Great location close to the center and a lovel...,Parking is across the street in a public garag...,Scored 10
7,Irene,Ireland,Comfort Double Room,3 nights ·,February 2025,Group,Great hotel - location was good,The staff were amazing! \nThe roof top bar was...,I couldn’t find a fault,Scored 10
8,Julie,United Kingdom,Comfort Single Room,3 nights ·,February 2025,Group,Exceptional,"Great location, comfortable room, food & wine ...",,Scored 10
9,R,Portugal,Comfort King Double Room with Romantic Package,1 night ·,February 2025,Couple,it was very good,"The room was nice, cosy and warm.",The sound proof could be a bit more efficient ...,Scored 8.0
10,Mcguinness,United Kingdom,Deluxe Panoramic Suite,3 nights ·,February 2025,Couple,Exceptional,"Great hotel,we loved our room with panoramic v...",,Scored 10
11,Marta,Portugal,Plus Comfort Suite,2 nights ·,February 2025,Family,Superb,"Room, location, staff",Breakfast,Scored 9.0
12,Alan,Ireland,Comfort Double Room,4 nights ·,February 2025,Family,Exceptional,"Location, rooms, cleanliness and the roof top ...",No complaints!,Scored 10
13,Mandy,Australia,Comfort King Room,3 nights ·,February 2025,Couple,Great value in a central and convenient locati...,Great location and a great view over Porto fro...,It exceeded all our expectations so no disappo...,Scored 9.0
14,Nazareth,France,Comfort Double Room,2 nights ·,January 2025,Couple,I recommend !!!,The breakfast is very good. The rooms are nice...,,Scored 9.0

In [36]:
df.tail(15)

,name,country,room_type,nr_nights,date,traveler_type,title_review,pos_review,neg_review,score
5022,Anonymous,France,Comfort Suite,3 nights ·,March 2023,Family,Very good,,,Scored 8.0
5023,Anonymous,France,Comfort King Room,1 night ·,March 2023,Couple,Exceptional,,,Scored 10
5024,Anonymous,Germany,Comfort Double Room,3 nights ·,February 2023,Group,Exceptional,,,Scored 10
5025,Anonymous,Luxembourg,Comfort Double Room,1 night ·,November 2022,Couple,Superb,,,Scored 9.0
5026,Anonymous,Ukraine,Comfort Double Room,1 night ·,May 2022,Family,Superb,,,Scored 9.0
5027,Anonymous,Belgium,Comfort King Room,4 nights ·,June 2022,Group,Superb,,,Scored 9.0
5028,Anonymous,Chile,Comfort Double Room,1 night ·,June 2022,Couple,Very good,,,Scored 8.0
5029,Anonymous,Germany,Comfort Family Room Plus,1 night ·,April 2022,Family,Exceptional,,,Scored 10
5030,Anonymous,Germany,Comfort Double Room,2 nights ·,March 2022,Couple,Superb,,,Scored 9.0
5031,Anonymous,Chile,Comfort Double Room,1 night ·,March 2022,Family,Very good,,,Scored 8.0
5032,Anonymous,Switzerland,Comfort Double Room,2 nights ·,June 2023,Couple,Good,,,Scored 7.0
5033,Anonymous,Czech Republic,Comfort Twin Room,2 nights ·,September 2022,Solo traveller,Good,,,Scored 7.0
5034,Anonymous,Portugal,Comfort Double Room,1 night ·,August 2022,Couple,Pleasant,,,Scored 6.0
5035,Anonymous,Chile,Comfort Twin Room,2 nights ·,July 2022,Family,Pleasant,,,Scored 6.0
5036,Anonymous,Spain,Comfort Double Room,1 night ·,February 2022,Family,Pleasant,,,Scored 6.0

In [38]:
# Saves the dataframes to .csv
df.to_csv("reviews_original.csv", index=False, encoding="utf-8")

In [42]:
df.head(5)

,name,country,room_type,nr_nights,date,traveler_type,title_review,pos_review,neg_review,score
0,Christina,Belgium,Comfort Double Room,3 nights ·,January 2025,Family,Exceptional,"Room was spacious, clean and with good amenities",NaN,Scored 10
1,Helen,United Kingdom,Comfort Single Room,2 nights ·,March 2025,Solo traveller,Well placed hotel with great facilities,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Scored 9.0
2,Irene,United Kingdom,Comfort King Room,2 nights ·,March 2025,Couple,Very clean with professional staff and very go...,Staff is very friendly and extremely professio...,Nothing,Scored 9.0
3,Andrea,Hungary,Plus Comfort Suite,4 nights ·,February 2025,Family,"Elegant, good hotel in the center",We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...",Scored 9.0
4,Anjali,Canada,Comfort Family Room,2 nights ·,February 2025,Family,Good location and nice hotel with spacious units.,Location and size of the unit. Comfortable for...,NaN,Scored 8.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5037 entries, 0 to 5036
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           5037 non-null   object
 1   country        5025 non-null   object
 2   room_type      5037 non-null   object
 3   nr_nights      5037 non-null   object
 4   date           5037 non-null   object
 5   traveler_type  5037 non-null   object
 6   title_review   5032 non-null   object
 7   pos_review     2482 non-null   object
 8   neg_review     1807 non-null   object
 9   score          5037 non-null   object
dtypes: object(10)
memory usage: 393.6+ KB

In [50]:
# Preenche NaN com "" vazias para não dar erro na tradução.
df['title_review'] = df['title_review'].fillna("")
df['pos_review'] = df['pos_review'].fillna("")
df['neg_review'] = df['neg_review'].fillna("")

In [54]:
translator = GoogleTranslator(source='auto', target='en')
df['pos_review_en'] = df['pos_review'].apply(lambda x : translator.translate(x))

In [72]:
df['neg_review_en'] = df['neg_review'].apply(lambda x : translator.translate(x))

In [77]:
df['title_review_en'] = df['title_review'].apply(lambda x : translator.translate(x))

In [78]:
df.head(5)

,name,country,room_type,nr_nights,date,traveler_type,title_review,pos_review,neg_review,score,pos_review_en,neg_review_en,title_review_en
0,Christina,Belgium,Comfort Double Room,3 nights ·,January 2025,Family,Exceptional,"Room was spacious, clean and with good amenities",,Scored 10,"Room was spacious, clean and with good amenities",,Exceptional
1,Helen,United Kingdom,Comfort Single Room,2 nights ·,March 2025,Solo traveller,Well placed hotel with great facilities,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Scored 9.0,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Well placed hotel with great facilities
2,Irene,United Kingdom,Comfort King Room,2 nights ·,March 2025,Couple,Very clean with professional staff and very go...,Staff is very friendly and extremely professio...,Nothing,Scored 9.0,Staff is very friendly and extremely professio...,Nothing,Very clean with professional staff and very go...
3,Andrea,Hungary,Plus Comfort Suite,4 nights ·,February 2025,Family,"Elegant, good hotel in the center",We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...",Scored 9.0,We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...","Elegant, good hotel in the center"
4,Anjali,Canada,Comfort Family Room,2 nights ·,February 2025,Family,Good location and nice hotel with spacious units.,Location and size of the unit. Comfortable for...,,Scored 8.0,Location and size of the unit. Comfortable for...,,Good location and nice hotel with spacious units.

In [111]:
# Saves the dataframes to .csv
df.to_excel("reviews_translated.xlsx", index=False, encoding="utf-8")
df.to_csv("reviews_translated_csv.csv", index=False, encoding="utf-8")

In [113]:
# Read translated xlsx
df = pd.read_csv("reviews_translated_csv.csv")

In [115]:
df

,name,country,room_type,nr_nights,date,traveler_type,title_review,pos_review,neg_review,score,pos_review_en,neg_review_en,title_review_en
0,Christina,Belgium,Comfort Double Room,3 nights ·,January 2025,Family,Exceptional,"Room was spacious, clean and with good amenities",NaN,Scored 10,"Room was spacious, clean and with good amenities",NaN,Exceptional
1,Helen,United Kingdom,Comfort Single Room,2 nights ·,March 2025,Solo traveller,Well placed hotel with great facilities,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Scored 9.0,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Well placed hotel with great facilities
2,Irene,United Kingdom,Comfort King Room,2 nights ·,March 2025,Couple,Very clean with professional staff and very go...,Staff is very friendly and extremely professio...,Nothing,Scored 9.0,Staff is very friendly and extremely professio...,Nothing,Very clean with professional staff and very go...
3,Andrea,Hungary,Plus Comfort Suite,4 nights ·,February 2025,Family,"Elegant, good hotel in the center",We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...",Scored 9.0,We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...","Elegant, good hotel in the center"
4,Anjali,Canada,Comfort Family Room,2 nights ·,February 2025,Family,Good location and nice hotel with spacious units.,Location and size of the unit. Comfortable for...,NaN,Scored 8.0,Location and size of the unit. Comfortable for...,NaN,Good location and nice hotel with spacious units.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5032,Anonymous,Switzerland,Comfort Double Room,2 nights ·,June 2023,Couple,Good,NaN,NaN,Scored 7.0,NaN,NaN,Good
5033,Anonymous,Czech Republic,Comfort Twin Room,2 nights ·,September 2022,Solo traveller,Good,NaN,NaN,Scored 7.0,NaN,NaN,Good
5034,Anonymous,Portugal,Comfort Double Room,1 night ·,August 2022,Couple,Pleasant,NaN,NaN,Scored 6.0,NaN,NaN,Pleasant
5035,Anonymous,Chile,Comfort Twin Room,2 nights ·,July 2022,Family,Pleasant,NaN,NaN,Scored 6.0,NaN,NaN,Pleasant
5036,Anonymous,Spain,Comfort Double Room,1 night ·,February 2022,Family,Pleasant,NaN,NaN,Scored 6.0,NaN,NaN,Pleasant

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5037 entries, 0 to 5036
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             5037 non-null   object
 1   country          5025 non-null   object
 2   room_type        5037 non-null   object
 3   nr_nights        5037 non-null   object
 4   date             5037 non-null   object
 5   traveler_type    5037 non-null   object
 6   title_review     5032 non-null   object
 7   pos_review       2482 non-null   object
 8   neg_review       1807 non-null   object
 9   score            5037 non-null   object
 10  pos_review_en    2482 non-null   object
 11  neg_review_en    1792 non-null   object
 12  title_review_en  5031 non-null   object
dtypes: object(13)
memory usage: 511.7+ KB